<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resposity\**" />
    <Content Remove="Resposity\**" />
    <EmbeddedResource Remove="Resposity\**" />
    <None Remove="Resposity\**" />
  </ItemGroup>

  <!-- <ItemGroup> -->
    <!-- <Compile Include="obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" /> -->
    <!-- <Compile Include="obj\Debug\net8.0\ProjectApi.AssemblyInfo.cs" /> -->
    <!-- <Compile Include="obj\Debug\net8.0\ProjectApi.GlobalUsings.g.cs" /> -->
  <!-- </ItemGroup> -->

  <ItemGroup>
    <Content Include="obj\Debug\net8.0\ApiEndpoints.json" />
    <Content Include="obj\Debug\net8.0\EndpointInfo\ProjectApi.json" />
    <Content Include="obj\Debug\net8.0\ProjectApi.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net8.0\staticwebassets.references.upToDateCheck.txt" />
    <Content Include="obj\Debug\net8.0\staticwebassets.removed.txt" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\ProjectApi.csproj.nuget.dgspec.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net8.0\" />
    <Folder Include="obj\Debug\net8.0\refint\" />
    <Folder Include="obj\Debug\net8.0\ref\" />
    <Folder Include="obj\Debug\net8.0\staticwebassets\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="obj\Debug\net8.0\apphost.exe" />
    <None Include="obj\Debug\net8.0\EndpointInfo\ProjectApi.OpenApiFiles.cache" />
    <None Include="obj\Debug\net8.0\project.razor.vs.bin" />
    <None Include="obj\Debug\net8.0\ProjectApi.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net8.0\ProjectApi.assets.cache" />
    <None Include="obj\Debug\net8.0\ProjectApi.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net8.0\ProjectApi.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net8.0\ProjectApi.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\project.nuget.cache" />
    <None Include="obj\ProjectApi.csproj.nuget.g.props" />
    <None Include="obj\ProjectApi.csproj.nuget.g.targets" />
  </ItemGroup>

</Project>
